# TensorFlow

TensorFlow Tutorials

## Basic Tensors and Operations

A tensor is a generalization of the scalar ($s \in \mathbb{R}$) the vector ($\vec{v} \in \mathbb{R}^n$) and the matrix ($M \in \mathbb{R}^{m \times n}$) to higher dimensions.

so a tensor is $t \in \mathbb{R}^{d_1 \times d_2 \times ... \times d_n}$ where $d_i$ is the dimension of the tensor in the $i$-th axis.

Note: That the tensor is not just a "real" number but can also be a complex number $t \in \mathbb{C}^{d_1 \times d_2 \times ... \times d_n}$ or even a boolean $t \in \{True, False\}^{d_1 \times d_2 \times ... \times d_n}$.

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.16.2'

In [3]:
tf.config.list_logical_devices()

2026-03-16 09:39:54.961259: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M5
2026-03-16 09:39:54.961303: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-03-16 09:39:54.961308: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2026-03-16 09:39:54.961474: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-03-16 09:39:54.961487: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

Creating a tensor with the identity matrix, the general identity matrix $I = \begin{bmatrix} 1 & \dots & 0 \\ \vdots & \ddots & \vdots \\ 0 & \dots & 1 \end{bmatrix}$ is a square matrix with ones on the diagonal and zeros elsewhere.

An important property of the identity matrix is that when it is multiplied by any other matrix, it leaves that matrix unchanged. For example, if $A$ is any matrix, then $I \cdot A = A \cdot I = A$.

In [4]:
a = tf.eye(4)
print(a)
print(a.device)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
/job:localhost/replica:0/task:0/device:CPU:0


Creating a tensor with all ones

In [5]:
b = tf.ones((4, 4))
b

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

Tensor addition, multiplication, subtraction and matrix multiplication

In [7]:
a + b
# or tf.add(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [1., 1., 2., 1.],
       [1., 1., 1., 2.]], dtype=float32)>

Note the difference between element-wise multiplication and matrix multiplication. Element-wise multiplication multiplies each corresponding element of the two tensors, while matrix multiplication involves multiplying the rows of the first tensor by the columns of the second tensor and summing the products to produce a new tensor.

In [8]:
a * b
# or tf.multiply(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [9]:
a - b
# or tf.subtract(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]], dtype=float32)>

In [10]:
a @ b
# or tf.matmul(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [11]:
zeros = tf.zeros((3, 4))
zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Creating random tensor with uniform or normal distribution

In [12]:
random_tensor = tf.random.uniform((3, 4), minval=0, maxval=10, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[5.2572060e+00, 5.2712202e-01, 5.4799881e+00, 2.5712240e+00],
       [7.3829699e+00, 3.1194091e-01, 3.2029486e+00, 9.0849285e+00],
       [3.6955214e+00, 3.4433579e+00, 6.4160957e+00, 6.9332123e-03]],
      dtype=float32)>

Testing the speed differences between GPU and CPU for matrix multiplication. Note: The speed difference will depend on the hardware you are running this on, and may not be significant for small matrices.

In [13]:
%%timeit
# do a 1024x1024 matrix multiplication on the GPU time it

if tf.config.list_physical_devices('GPU'):
    with tf.device('GPU:0'):
        random_matrix1 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
        random_matrix2 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
        result = random_matrix1 @ random_matrix2
else:
    print("No GPU found. Running on CPU.")

741 μs ± 19.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
%%timeit
# do the same on the CPU and time it

with tf.device('CPU:0'):
    random_matrix1 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
    random_matrix2 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
    result = random_matrix1 @ random_matrix2


3.9 ms ± 239 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Here we see a matrix multiplication on GPU of two $1024\times 1024$ matrices took $770\mu s$ while the same operation on CPU took $3.86 ms$ which is about 5 times slower than the GPU. Note that the speed difference will depend on the hardware you are running this on, and may not be significant for small matrices.

# PyTorch

PyTorch Tutorials:

PyTorch is an open-source machine learning library developed by Facebook's AI Research lab (FAIR). It provides a flexible and dynamic computational graph, making it easier to build and train deep learning models. PyTorch is widely used in both academia and industry for various applications, including natural language processing, computer vision, and reinforcement learning.

In [15]:
# tensor in PyTorch
import torch

In [16]:
torch.__version__

'2.10.0'

In [19]:
# list all devices available (we are on macOS)
torch.cuda.is_available()

False

In [20]:
torch.backends.mps.is_available()

True

In [21]:
# run the matrix multiplication test on Apple Metal Performance Shaders (MPS)

mps_device = torch.device('mps') if torch.backends.mps.is_available() else None
mps_device

device(type='mps')

Testing the speed differences between MPS and CPU for matrix multiplication in PyTorch. On macOS, PyTorch uses Apple's Metal Performance Shaders (MPS) backend instead of CUDA. The exact speedup will depend on your hardware, PyTorch version, and whether MPS is available.

In [22]:
%%timeit
# do a 1024x1024 matrix multiplication on MPS and time it

if torch.backends.mps.is_available():
    random_matrix1 = torch.rand((1024, 1024), device='mps')
    random_matrix2 = torch.rand((1024, 1024), device='mps')
    result = random_matrix1 @ random_matrix2
    torch.mps.synchronize()
else:
    print("MPS not available. Skipping MPS benchmark.")


889 μs ± 2.34 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [23]:
%%timeit
# do the same on the CPU and time it

random_matrix1 = torch.rand((1024, 1024), device='cpu')
random_matrix2 = torch.rand((1024, 1024), device='cpu')
result = random_matrix1 @ random_matrix2


3.37 ms ± 112 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


If MPS is available, you can compare its timing with the CPU timing above. Keep in mind that results may vary from run to run, and the first run on MPS can include initialization overhead. For accurate MPS timings, we explicitly synchronize after the matrix multiplication.
