# TensorFlow

TensorFlow Tutorials

## Basic Tensors and Operations

A tensor is a generalization of the scalar ($s \in \mathbb{R}$) the vector ($\vec{v} \in \mathbb{R}^n$) and the matrix ($M \in \mathbb{R}^{m \times n}$) to higher dimensions.

so a tensor is $t \in \mathbb{R}^{d_1 \times d_2 \times ... \times d_n}$ where $d_i$ is the dimension of the tensor in the $i$-th axis.

Note: That the tensor is not just a "real" number but can also be a complex number $t \in \mathbb{C}^{d_1 \times d_2 \times ... \times d_n}$ or even a boolean $t \in \{True, False\}^{d_1 \times d_2 \times ... \times d_n}$.

In [28]:
import tensorflow as tf

In [29]:
tf.__version__

'2.16.2'

In [30]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

Creating a tensor with the identity matrix, the general identity matrix $I = \begin{bmatrix} 1 & \dots & 0 \\ \vdots & \ddots & \vdots \\ 0 & \dots & 1 \end{bmatrix}$ is a square matrix with ones on the diagonal and zeros elsewhere.

An important property of the identity matrix is that when it is multiplied by any other matrix, it leaves that matrix unchanged. For example, if $A$ is any matrix, then $I \cdot A = A \cdot I = A$.

In [31]:
a = tf.eye(4)
print(a)
print(a.device)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
/job:localhost/replica:0/task:0/device:CPU:0


Creating a tensor with all ones

In [32]:
b = tf.ones((4, 4))
b

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

Tensor addition, multiplication, subtraction and matrix multiplication

In [33]:
 a + b
# or tf.add(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [1., 1., 2., 1.],
       [1., 1., 1., 2.]], dtype=float32)>

Note the difference between element-wise multiplication and matrix multiplication. Element-wise multiplication multiplies each corresponding element of the two tensors, while matrix multiplication involves multiplying the rows of the first tensor by the columns of the second tensor and summing the products to produce a new tensor.

In [34]:
a * b
# or tf.multiply(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [35]:
a - b
# or tf.subtract(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]], dtype=float32)>

In [36]:
a @ b
# or tf.matmul(a, b)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [37]:
zeros = tf.zeros((3, 4))
zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Creating random tensor with uniform or normal distribution

In [38]:
random_tensor = tf.random.uniform((3, 4), minval=0, maxval=10, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[5.221641 , 5.009102 , 7.271184 , 7.038386 ],
       [5.8539104, 9.900274 , 3.4758496, 5.0652266],
       [6.891651 , 7.58893  , 4.7113743, 8.780513 ]], dtype=float32)>

Testing the speed differences between GPU and CPU for matrix multiplication. Note: The speed difference will depend on the hardware you are running this on, and may not be significant for small matrices.

In [39]:
%%timeit
# do a 1024x1024 matrix multiplication on the GPU time it

if tf.config.list_physical_devices('GPU'):
    with tf.device('GPU:0'):
        random_matrix1 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
        random_matrix2 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
        result = random_matrix1 @ random_matrix2
else:
    print("No GPU found. Running on CPU.")

769 μs ± 34.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [40]:
%%timeit
# do the same on the CPU and time it

with tf.device('CPU:0'):
    random_matrix1 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
    random_matrix2 = tf.random.uniform((1024, 1024), minval=0, maxval=10, dtype=tf.float32)
    result = random_matrix1 @ random_matrix2


3.83 ms ± 151 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Here we see a matrix multiplication on GPU of two $1024\times 1024$ matrices took $770\mu s$ while the same operation on CPU took $3.86 ms$ which is about 5 times slower than the GPU. Note that the speed difference will depend on the hardware you are running this on, and may not be significant for small matrices.